### ISSUE TITLE
Rails 4.2 searching on relations fails

### ISSUE THREAD

**Issue by danlewis** [wvanbergen/scoped_search#115]
class Review < ActiveRecord::Base
      scoped_search on: [:comment, :status]
      scoped_search in: :user, on: [:first_name, :last_name, :email]
      belongs_to :user
    end

The following search fails in Rails 4.2 with the error: "relation 'user' not one of user"

    Review.search_for('I do say old gent this does appear to be broken')

This happens on all my rails 4.2 apps where models use the in method

**Comment by wvanbergen** [comment]
- I enabled testing against ActiveRecord 4.2: https://github.com/wvanbergen/scoped_search/pull/116. 
- Many tests are failing: https://travis-ci.org/wvanbergen/scoped_search/jobs/46981127

**Comment by wvanbergen** [comment]
I fixed some of these issues, but not all, in #116. Can you try that branch to see if it is working for you?

**Comment by danlewis** [comment]
The issue was resolved after switching to the branch ar_42

**Comment by wvanbergen** [comment]
Perfect. Once I fix the remaining failing test cases, I'll merge that branch and do a new release.

**Comment by quantumpotato** [comment]
Thanks
