### ISSUE TITLE
Add validations to fields

### ISSUE THREAD

**Issue by ShimShtein** [wvanbergen/scoped_search#148]
Add an option to specify validation method while specifying a field to search:

``` ruby
scoped_search :on => :owner_id, :complete_enabled => false, :only_explicit => true, :validator => ->(value) { value.is_a? Integer }
```

It will require a new attribute in [definition.rb](https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/definition.rb). The attribute will be checked in [query_builder.rb](https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/query_builder.rb#L213) and the query will be rejected, if the validator fails.

**Comment by wvanbergen** [comment]
Can you elaborate a bit on your use case for this?

**Comment by ShimShtein** [comment]
Sure. Let's examine the example I have provided: I want to enable search on `:owner_id` column that is actually an integer. The problem is that if I write:
``` ruby
Host.search_for('owner_id = zzz').first
```
It will fail with `ActiveRecord::StatementInvalid: PG::Error`. I don't want to bubble SQL exceptions all the way up to the user, so I prefer to validate the query before I send it to the database.
Basically my strict requirement is to identify string inputs for numeric columns, but while at it I thought it would be nice to enable custom validators for the input. This way I could validate more complex logic, like IP pattern for string columns that are used to store IP's and so on.

**Comment by ShimShtein** [comment]
@wvanbergen Do you have any plans to look at this issue/PR?

**Comment by kgaikwad** [comment]
@wvanbergen , 
I am also facing the similar kind of situation where I don't want to bubble SQL exception.
When you are planning to merge the PR given by @ShimShtein for an issue?

**Comment by ShimShtein** [comment]
Closing the issue, since the feature was merged.
