### ISSUE TITLE
Request for new gem release

### ISSUE THREAD

**Issue by thomasmckay** [wvanbergen/scoped_search#165]
Could a new gem release be made to include https://github.com/wvanbergen/scoped_search/issues/162 please? This is to allow it to be included in foreman-1.15 upcoming release.
Thanks!

**Comment by wvanbergen** [comment]
Waiting for one PR to be done, will do a new release afterwards.

**Comment by wvanbergen** [comment]
@domcleal Are we ready for a new release? We may need to update the changelog

**Comment by domcleal** [comment]
Yes, I think so! 4.1.0 published.
