### ISSUE TITLE
A new release required

### ISSUE THREAD

**Issue by ares** [wvanbergen/scoped_search#169]
Hello @wvanbergen, could we please get a new release that contains https://github.com/wvanbergen/scoped_search/commit/80d0a9f3c235d3df49e355bd6750b0728481d8f3? I'd love to do that but I don't have a permissions on pushing to repo and rubygems.org. Thank you.

**Comment by wvanbergen** [comment]
4.1.1 has been pushed to rubygems,

**Comment by wvanbergen** [comment]
@ares What is your account on Rubygems.org?

**Comment by ares** [comment]
It's ares[at]igloonet.cz, thank you very much!

**Comment by wvanbergen** [comment]
Added!

**Comment by ares** [comment]
Thank you
