### ISSUE TITLE
Question: Can the advanced query language be disabled?

### ISSUE THREAD

**Issue by K1N5L4Y3R** [wvanbergen/scoped_search#177]
This gem works great for us, specially in 'admin' controllers in which we can query exactly what we need.

However, we are also using this for 'regular' controllers (i.e. the ones that any user has access to). We would like to have these searches only work for 'words' or 'phrases' (as per [this README table](https://github.com/wvanbergen/scoped_search#query-language)). The reason for this is, we would like to not expose our database structure by explicit searches, prevent some errors that come from querying something with the wrong format, and just overall make it as simple as possible for users to do simple searches.
Can this be done in some way? We could manually add quotes before and after the query so that it only looks for exact phrases, but this wouldn't work for 'words'. Are we better of not using scoped_search for this and just having a normal scope with `ILIKE` for the fields that we want to search?

**Comment by wvanbergen** [comment]
You can specify different `profiles`, one for admin users, and one for regular users.

I don't think you can easily limit what kind of search constructs are supported in the query language though. You can limit access to fields in your DB, but AFAIK the fields that a user does have access to can be referred to by name in the query language.

I'd say that building your own scope with ILIKE is probably easier to accomplish this vs. (monkey)patching scoped search to do this.
