### ISSUE TITLE
Using like operator produces case sensitive results

### ISSUE THREAD

**Issue by serogers** [wvanbergen/scoped_search#19]
The documentation mentions that when using the LIKE operator, the search should be case insensitive.  However, I cannot seem to get this to work.  All my searches are case sensitive.  Below is what I have done, am I missing something?
### DATABASE

MySQL
"content" attribute is a varchar
### RAILS

Rails: 3.1, Ruby: 1.8.7
### SCOPE

scoped_search :on => :content, :default_operator => :like
### SEARCH

Post.search_for("Attempt")
### GENERATED QUERY

SELECT `posts`.\* FROM `posts` WHERE ((`posts`.`content` LIKE '%Attempt%'))
### ACTUAL POST CONTENT

This is a test, attempt #3

Since the post contains the word "attempt" as a lower case word, this record isn't found when searching "Attempt".  How can I make this case insensitive.  Other than this issue, I am loving the gem! Thanks for your help.

**Comment by owenwiddicombe** [comment]
I need to be able to query an Oracle Database that is case sensitive.  I would like the searches to be case-insensitive.  I have no control over the external Oracle database and cannot change the collation.  Presumably it is case sensitive for a reason.  How can I use scoped_search to find case insensitive results?
