### ISSUE TITLE
Postgres adapter not picked up when using PostGIS

### ISSUE THREAD

**Issue by cliffrowley** [wvanbergen/scoped_search#190]
When using PostGIS, the adapter is actually `ActiveRecord::ConnectionAdapters::PostGISAdapter` so it's not picked up by the following code:

https://github.com/wvanbergen/scoped_search/blob/d235d5fd13c360877e22828b9d897e605dbaa150/lib/scoped_search/query_builder.rb#L32

This means that the default (MySQL) adapter is being used instead.

**Comment by wvanbergen** [comment]
This should be a simple fix. I am not working on this library myself anymore, but will happily accept a PR that fixes this.
