### ISSUE TITLE
"undefined method `to_sym' for {:on=>:looking_for}:Hash\nDid you mean? to_s\n to_set"

### ISSUE THREAD

**Issue by mjesar** [wvanbergen/scoped_search#203]
I just upgraded the project to Ruby 3.0.0 from 2.7.2 and it giving an error on `scoped_search on: :looking_for` in model file 
Any have any solution to this

**Comment by anderscarling** [comment]
I run this workaround:

```
require 'scoped_search'
if ScopedSearch::VERSION != "4.1.9"
  raise "Assess if fix is still nessecary"
end

module ScopedSearchDefinitionRuby3Fix
  def define(*args)
    options = args.extract_options!
    ScopedSearch::Definition::Field.new(self, *args, **options)
  end
end
ScopedSearch::Definition.prepend(ScopedSearchDefinitionRuby3Fix)
```

(I load it by placing it in a file in `lib/extensions/scoped_search_definition_ruby_3_fix.rb` and doing `require File.expand_path("../lib/extensions/scoped_search_definition_ruby_3_fix.rb", __dir__)` just after `Bundler.require(*Rails.groups)` in `config/application.rb`)

**Comment by anderscarling** [comment]
Note that it will cause an exception on rails boot if ScopedSearch version is no longer 4.1.9 to make sure I remember to validate if its still needed.
