### ISSUE TITLE
rubygems.org version differs from master branch, Ruby 3 support not included

### ISSUE THREAD

**Issue by D4uS1** [wvanbergen/scoped_search#214]
Hi Guys,

there was recently a [commit](https://github.com/wvanbergen/scoped_search/commit/adf203dd5b736550ef1911623c935acdca8635a8#diff-624f1c37977180058e03013342c7ed3b2785ff739ec1f0a82ba2d99278f472df) to enable Ruby 3 support. 
The current version of the Gem 4.1.9 is listed in [rubygems.org](https://rubygems.org/gems/scoped_search) but seems not to include those fix.

Currently i am using the gem by referencing to the github repo.

`
gem 'scoped_search', git: 'https://github.com/wvanbergen/scoped_search.git'
`

Can we have some update on rubygems.org to make it available without referencing to the repository?

Thank you
D4uS1

**Comment by adamruzicka** [comment]
Version 4.1.10 containing, among other things, ruby 3 compatibility was just released to rubygems.

**Comment by D4uS1** [comment]
Sounds great 👍 . Thank you very much!
